-- View: vw_active_customers
-- Purpose: Identify customers with recent activity (last 30 days) and compute active metrics
-- Business metric: Rolling 30-day active customer count, order frequency, and revenue
-- Refresh strategy: Automatically recomputed on each query execution (dynamic view)
-- Used by: Executive Dashboard, Customer Success Dashboard, Retention Analytics
-- 
-- Columns:
--   customer_id: Unique customer identifier (Primary Key)
--   customer_name: Display name of the customer
--   segment: Business tier classification (Enterprise, Mid-Market, SMB, Starter)
--   order_count_30d: Count of distinct orders placed within the last 30 days
--   revenue_30d: Total revenue generated by customer in the last 30 days
--   last_order_date: Timestamp/date of customer's most recent order
--   days_since_order: Days elapsed since customer's last order

CREATE VIEW IF NOT EXISTS vw_active_customers AS
SELECT 
    c.customer_id,
    c.customer_name,
    c.segment,
    COUNT(DISTINCT o.order_id) as order_count_30d,
    COALESCE(SUM(o.order_amount), 0.0) as revenue_30d,
    MAX(o.order_date) as last_order_date,
    CAST(ROUND(julianday('now') - julianday(MAX(o.order_date))) AS INTEGER) as days_since_order
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
    AND o.order_date >= date('now', '-30 days')
WHERE c.deleted_at IS NULL
GROUP BY c.customer_id, c.customer_name, c.segment;
