-- View: vw_product_performance
-- Purpose: Compute product-level sales metrics, total quantity sold, revenue, and customer reach
-- Business metric: Evaluates product performance, catalog velocity, and monetization efficiency
-- Refresh strategy: Automatically recomputed on each query execution (dynamic view)
-- Used by: Operations Dashboard, Product Management Team, Inventory Planning
--
-- Columns:
--   product_id: Unique product identifier
--   product_name: Name of the product
--   category: Product category classification
--   unit_price: Current listing price per product unit
--   total_units_sold: Aggregate quantity of product units sold all-time
--   total_product_revenue: Gross revenue generated by product
--   unique_purchasers: Number of distinct customers who purchased this product
--   avg_order_value_per_prod: Average transaction value for orders containing this product

CREATE VIEW IF NOT EXISTS vw_product_performance AS
SELECT 
    p.id as product_id,
    p.product_name,
    p.category,
    p.price as unit_price,
    COALESCE(SUM(o.quantity), 0) as total_units_sold,
    COALESCE(SUM(o.order_amount), 0.0) as total_product_revenue,
    COUNT(DISTINCT o.customer_id) as unique_purchasers,
    COALESCE(ROUND(AVG(o.order_amount), 2), 0.0) as avg_order_value_per_prod
FROM products p
LEFT JOIN orders o ON p.id = o.product_id
GROUP BY p.id, p.product_name, p.category, p.price;
